name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud Foundry CLI
      uses: elliottpope/cloudfoundry-cli-action@v2
      with:
        api: ${{ secrets.CF_API }}
        organization: msd
        space: ctaas
        
    - name: SSO Login
      run: |
        cf login --sso

    - name: Input SSO Temporary Code
      run: |
        echo "Please input the SSO temporary code provided by Cloud Foundry: "
        read sso_temporary_code
        cf login --sso -c ${{ secrets.CF_SSO_PASSCODE }}

    - name: Deploy to Cloud Foundry
      run: cf push
