name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: download cf-cli
      run: |
        sselga-assurity/github-grafana-manifest/steps/download-cf-cli.sh

    - name: deploy dashboard
      run: |
        sselga-assurity/github-grafana-manifest/steps/deploy-app.sh
