name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: download cf-cli
      run: |
        ${{secrets.GITHUB_WORKSPACE}}/steps/download-cf-cli.sh

    - name: deploy dashboard
      run: |
        ${{secrets.GITHUB_WORKSPACE}}/steps/deploy-app.sh