name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: print current dir
      run: pwd
    
    - name: download cf-cli
      run: |
        chmod +x download-cf-cli.sh

    - name: deploy dashboard
      run: |
        chmod +x /home/runner/work/github-grafana-manifest/github-grafana-manifest/steps/deploy-app.sh
