name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

env:
  CF_USERNAME: ${{ secrets.CF_USERNAME }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_ORG: ${{ secrets.CF_ORG }}
  CF_SPACE: ${{ secrets.CF_SPACE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: download cf-cli
      run: |
        chmod +x /home/runner/work/github-grafana-manifest/github-grafana-manifest/steps/download-cf-cli.sh
        /home/runner/work/github-grafana-manifest/github-grafana-manifest/steps/download-cf-cli.sh

    - name: deploy dashboard
      run: |
        chmod +x /home/runner/work/github-grafana-manifest/github-grafana-manifest/steps/deploy-app.sh
        /home/runner/work/github-grafana-manifest/github-grafana-manifest/steps/deploy-app.sh
