name: upload grafana board
on:
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: upload grafana board
        run: |
          cd .\grafana-config\
          cf push