name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud Foundry CLI
      uses: cloudfoundry/cli-action@v2
      with:
        cf_api: ${{ secrets.CF_API }}
        cf_sso: true
        cf_sso_passcode: ${{ secrets.CF_SSO_PASSCODE }}
        
    - name: Login to Cloud Foundry
      run: cf login --sso
        
    - name: Deploy to Cloud Foundry
      run: cf push -o msd -s ctaas
