name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Cloud Foundry CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf-cli
        
    - name: Set up Cloud Foundry API endpoint
      run: cf api ${{ secrets.CF_API }}
        
    - name: SSO Login
      run: |
        cf login --sso-passcode ${{ secrets.CF_SSO_PASSCODE }}

    - name: Target Cloud Foundry Org and Space
      run: |
        cf target -o msd -s ctaas

    - name: Change to grafana-config directory
      run: cd ./grafana-config/

    - name: Deploy to Cloud Foundry
      run: cf push dashboard-trends-grafana
