name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

env:
  CF_API:  ${{ secrets.CF_API }}
  CF_USERNAME: ${{ secrets.CF_USERNAME }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_ORG: ${{ secrets.CF_ORG }}
  CF_SPACE: ${{ secrets.CF_SPACE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test jq
      run: |
        export CF_ORG="fOO"
        echo $CF_ORG

    - name: deploy
      run: |
        echo $CF_ORG

    # - name: download cf-cli
    #   run: |
    #     chmod +x ${GITHUB_WORKSPACE}/steps/download-cf-cli.sh
    #     ${GITHUB_WORKSPACE}/steps/download-cf-cli.sh
     
    # - name: deploy dashboard        
    #   run: |
    #     chmod +x ${GITHUB_WORKSPACE}/steps/deploy-app.sh
    #     ${GITHUB_WORKSPACE}/steps/deploy-app.sh
