name: Deploy to Cloud Foundry

on:
  workflow_dispatch:  # This allows manual triggering of the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cloud Foundry CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates wget gnupg
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install -y cf-cli
        
    - name: Login to Cloud Foundry
      run: |
        cf api ${{ secrets.CF_API }}
        cf auth seph.selga@assurity.co.nz ${{ secrets.CF_SSO_PASSWORD }}
        cf target -o msd -s ctaas
        
    - name: Deploy to Cloud Foundry
      run: |
        cf push
